### ISSUE TITLE
3D matching

### ISSUE THREAD

**Issue by ligaoqi2** [ultravideo/Stereo-3D-Pose-Estimation#3]
I have a question about the 3D pose generation.
It is reasonable to use triangulation to output 3D coordinates, but how to ensure that the proposed joint points of the left and right images are the same point? For example, the person’s hip detected on the left will have a certain deviation in the right eye, and may not be the same point (such as the corner point of the checkerboard, which corresponds to only one point in the left and right eyes, but the point estimated by the pose is not necessarily a point. ), isn’t the 3D coordinate output from the same point still reasonable?

**Comment by teo3n** [comment]
> but how to ensure that the proposed joint points of the left and right images are the same point

In theory, "you don't". There is no guarantee they indeed *are* the exact same point, however, in practice the difference is so minor the resulting 3D pose is good. How the cameras are configured also plays a major role; use a standard stereo configuration with e.g. 16cm of IPD or baseline will mean there is very minimal shift between the views.

**Comment by ligaoqi2** [comment]
OK, thank you for your patience, the effect I reconstructed with my own camera is not good, can you provide the two avi video files used in your experiment? I just want to use it to experiment and see the effect of the final 3D reconstruction. My email is ligaoqi02@gmail.com. Another question I want to ask you is whether the unit of camera_dist in line 39 of pose3d.py is meter or millimeter , and how is the camera_pixel_dev in line 41 obtained? It seems that there is no such variable in the calibration camera

**Comment by teo3n** [comment]
I don't think those video files exist anymore anywhere, unfortunately. `camera_dist` is in meters and `camera_pixel_dev` is used to filter out invalid poses (i.e. body point-correspondences with more than `camera_pixel_dev` amount of delta). It's a 100% guesstimated value, pick whatever works in your approach.

**Comment by ligaoqi2** [comment]
Ok, thanks for your help
